nelchess@gmail.com

2. Клиенты, которые знают и занимаются ASO
Можете рассказать немного о вашей компании и вашем приложении?
Работали ли вы раньше с ASO ?
Какие платформы – iOS, Android ?
Как продвигаете сейчас приложение ?
В каких странах вы продвигаете свое приложение?
Как давно вы занимаетесь ASO? Какими инструментами пользовались ASO?
Ранее пользовались платформами как Asodesk?
Какие у вас основные сложности в ASO?
Используете ли вы автоматизированные решения для работы с отзывами?
Как часто вы обновляете метаданные и тестируете изменения?


ASO tools - раздел где находятся основные инструмент для работы и анализа ключевых слов и приложений.
App profile - показывает всю информацию, которая видна на страничке приложения в сторе пользователю
=============================
ASO Comparative Report - инструмент показывающий уровень индексации приложения; список индексируемых кейвордов и сравнение метаданных приложения. Все то же можем увидеть и для приложений конкурентов.
Keyword ranking distribution - график индексации кейвордов приложения. (Пояснение -  мы видим сколько ключевых слов  попадают в конкретный промежуток позиций (топ)).
Semantic Chart- Та же информация что и на графике Keyword ranking distribution, но в другой визуализации
Topbox - удобные фильтры по топам кейвордов,  с сортировкой keywordoв по динамике в этом промежутке позиций
Кнопка show details под этими фильтрами  открывают список ключей, которые находились в этом промежутке позиций за выбранный период.
*обозначить столбцы c показателями сравнения Previous и Current
Daily impressions - Трафик за день
Rank- позиция
Movement - динамика изменения позиций
Снизу таблицы сравнение метаданных приложения за выбранный промежуток времени + инфо по in-apps (инапы)
===========================================================
Traffic sourses - Инструмент показывает с какого источника трафика приложение получает органические установки, при наличии интеграции с ASC (App Store Connect)
Impressions, App Units, CVR -   график показывает конверсии из просмотров в установку за выбранный период времени
Product Page Views, App Units, CVR - график показывает конверсию из просмотра страницы приложения в установку за выбранный период времени
Есть фильтр по источникам трафика и по странам
Можно переключить из app units (уникальная установка или первая установка на устройство) в instalations (любая последующая установка на устройство)
Эти же графики можно отобразить в текстовом формате, а если экспортировать то мы получим красивую сводную таблицу в excel.
==================================================
Keywordhighlights - Здесь у нас highlightы по отдельным keywordам и можем отслеживать их динамику
New Keywords- Новые ключи по которым приложение начало индексироваться
Lost Keywords- Ключи по которым приложение перестало индексироваться
Positive movement- По данным ключам приложение начало ранжироваться выше(Показывает позитивную динамику)
Negative movement - По данным ключам приложение потеряло позиции (Показывает негативную динамику)
==========================================================
Categories Ranking - Позиция приложения в категории. График показывает историю позиций приложения в категории.
Кнопка summary - показывает позиции в категории по разным странам
====================================================================================
ORGANIC REPORT -тут мы найдем полный список индексируемых ключей (я бы этот момент обозначала как один из основных)  по каким ключам и сколько приложение получает органические установки + 
Totatl organic history- тут рассчётные данные по органическим установкам за последние 12 дней
Пайчарт - который дублирует информацию из таблицы ниже
Total keywords- тут таблица всех кейвордов по которым индексируется приложение, в отличии от comparative report, тут есть ключи с 0-ым трафиком и кейворды до 250 ранка\позиции
total istall share -  алгоритм, показывающий процентное соотношение установок по кейвордам \ распределение установок \ доля органических установок которая приходится на данное ключевое слово
estimated installs - рассчетное количество установок за день
========================================================
FIND AND TRACK - инструмент где хранятся все ключи которые мы добавили к себе в аккаунт он - разделён на 3 части
Keyword Manager- здесь легко можем найти и добавить нужные ключи, можно вписывать вручную.
Missing Ranked Keywords - ключи по которым наше приложение индексируется, но мы ещё не добавили их к себе, сортированные по топам
Missing Competitor Keywords - ключи, по которым индексируется приложение конкурента. При сохранении ключ исчезает из списка (демонстрируем)
Apple Search Ads Suggestions - саджесты от apple search ads \ из кабинета apple search ads
text analyser - инструмент для анализа описания тут виден анализ описания нашего приложения на количество и густоту использования keywordов
keywordshuffler -инструмент для создания комбинации keywordov
Copy form - инструмент который помогает нам скопировать kewwordy из одной локали в другую
keyword ranking chart -исторические данные по позициям по выбранному keyword (можно выбрать до 10 ключей)
Keyword Table- тут отображаются только те ключи, которые мы добавили себе в аккаунт
Есть возможность сортировать ключи по вкладкам, добавлять заметки, отмечать цветом, удобный фильтр по поиску + смарт чекбокс
Можно редактировать\ настраивать таблицу под свои задачи.
кнопка live- показывает поисковую выдачу по ключевому слову
кнопке explore - поисковая выдача по ключевому слову с экшн баттон
dynamics - тотже график из caompatitor report только не по всем keywordam а по тем которым мы добавили к себе - график индексации по сохраненным ключам + сравнение DI и позиций (start\end)
==================================================
charts- инструмент для визуального анализа поисковой выдачи и отбора релевантных кейвордов  \ \ инструмент который показывает топ 10 позиций по нашим keywordу с иконками, оттуда же можно удалять keyword
График показывает историю позиций по ключевым словам
===========================================
Competitors Positions - Инструмент показывает позиции добавленных конкурентов по сохранённым ключам
График показывает историю позиций конкурентов в сравнение с нашим приложениям по выбранным ключам
==================================================
Phrase Mixer - инструмент для создания комбинации keywordov
============================================================
Live position- Это Эмулятор строки поиска в выбранном сторе.
Profile - вкладка показывает профиль ключа.озицию в сторах по странам, трафик, searchads popularity, количество приложений индексируемых по ключу в конкретной стране
=================================
charts- инструмент который показывает топ 10 выдач по нашим keywordу
если отслеживаемое приложение находится ниже 10ой позиции , это тоже показывается
===============================
Autosuggestion - собирает все ключи в индексации нашего приложения и добавленных конкурентов и сортирует их по группам 
Most popular - самые трафиковые ключи
Competitors Best keywords - Наиболее популярные поисковые запросы в тематике у конкурентов, откуда они получают установки
Long tail keyword -Длинные запросы, которые состоят от 3 и более слов
Least Competetive Key - Наименее конкурентные запросы, где количество ранжируемых приложений меньше
Кейворды для кейворд бустинга - не актуально
Expected to be Trending -  возможно могут появиться в ближайшее время в трендах
================================
Description Creator - работа с полным описанием приложения
=================================
Text Metadata Builder - работа с текстовыми метаданными
так же отображаются дополнительные языки
Кнопка Save сохраняет вписанные и добавленные метаданные, чтобы можно было вернуться к прошлым вариантам тестировать разные наборы метаданных.
Count- обновляет статистику и добавляет keyword которые мы вписали
UnUsed Report - ключи которые мы ещё не добавили из Keyword Table
Used Report  - добавленные ключи в текст. метаданные из списка unused report
Search Queries Report  - возможные комбинации ключей которые мы использовали
=====================================
Stores analitycs - Аналитика по сторам инструменты с данными из сторов (без привязки к приложению)
Search Explorer - Это Эмулятор строки поиска в выбранном сторе.Если  выбрать один стор, то появится action button.
Top Charts - категории в сторах
CVR Benchmarks - инструмент который показывает конверсию в установки для игр и других приложений отдельно
Top Keywords - Список самых популярных keywordов по странам и сторам
App Store Trending Searches - показывает трендовые запросы по датам в app store.
=============================================
Reviews & Replies - работа с отзывами \ review management
Reviews & Replies Board - Ручная работа с отзывами + просмотр списка отзывов, выгрузка.
Featured Reviews - зафичеренные отзывы приложения
Reviews Analysis - анализ отзывов
Rating Analysis - анализ по оценкам приложения
Tag Analysis - анализ тегированных отзывов\ анализ проставленных тегов
Templates - шаблоны
Autoreplies - автоматизация процесса ответов на отзывы
Create new rule - создание правил/условий автоматического ответа на отзыв
Tags
Autotags
Connections hub
All Reports Settings - создание репортов
Reports Timeline - история репортов
Integrations - интеграции
API - интеграция по API что получать информацию от нас \ апи тарифы
Keyword Boost - создание компании по мотивированным установкам приложения по ключевым словам.